### ISSUE TITLE
Errors with engineio 3 version due to not pinned major version in setup.py

### ISSUE THREAD

**Issue by tmbo** [miguelgrinberg/python-socketio#218]
Engineio released a version 3.0.0 - which, as expected, is not backwards compatible.

Do you mind creating a bug fix release where you pin the engineio version in `setup.py`, e.g. using 
`'python-engineio>=2.2.0,<3'`

Currently an installation will pull 3.0.0 and result in the following exception for us:
```
core_1           | Traceback (most recent call last):
core_1           |   File "/usr/local/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
core_1           |     self.run_application()
core_1           |   File "/usr/local/lib/python3.6/site-packages/gevent/pywsgi.py", line 908, in run_application
core_1           |     self.result = self.application(self.environ, self.start_response)
core_1           |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
core_1           |     return self.wsgi_app(environ, start_response)
core_1           |   File "/usr/local/lib/python3.6/site-packages/engineio/middleware.py", line 63, in __call__
core_1           |     [('Content-Type', self.static_files[path]['content_type'])])
core_1           | TypeError: string indices must be integers
core_1           | Wed Dec  5 13:27:53 2018 {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '45868', 'HTTP_HOST': 'localhost:5005', (hidden keys: 18)} failed with TypeError
core_1           |
```

**Comment by miguelgrinberg** [comment]
This is actually a bug, it wasn't supposed to break existing apps. I'll fix it.

**Comment by tmbo** [comment]
Here is the code: https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/channels/socketio.py#L23

Which freeze do you mean, the breaking one or the working one?

**Comment by tmbo** [comment]
Doesn't seem to work with engineio 2.3.x either, 
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/travis/build/RasaHQ/rasa_core/rasa_core/agent.py", line 17, in <module>
    from rasa_core.channels import UserMessage, OutputChannel, InputChannel
  File "/home/travis/build/RasaHQ/rasa_core/rasa_core/channels/__init__.py", line 11, in <module>
    from rasa_core.channels.socketio import SocketIOInput
  File "/home/travis/build/RasaHQ/rasa_core/rasa_core/channels/socketio.py", line 5, in <module>
    import socketio
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/socketio/__init__.py", line 10, in <module>
    from .middleware import WSGIApp, Middleware
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/socketio/middleware.py", line 4, in <module>
    class WSGIApp(engineio.WSGIApp):
AttributeError: module 'engineio' has no attribute 'WSGIApp'
```
pinned it to 2.2.0 for our project now.

**Comment by miguelgrinberg** [comment]
That's fine, the code gave me what I needed. I'll have a fix up in a bit.

**Comment by tmbo** [comment]
Awesome :heart:

**Comment by tmbo** [comment]
Ah ok, so it should rather be
```
app.wsgi_app = socketio.Middleware(socketio_app=self.sio, wsgi_app=app.wsgi_app,
                                           socketio_path=self.socketio_path)
```
?

**Comment by miguelgrinberg** [comment]
@tmbo that would fix the problem. But I'm also going to revert the order of the arguments in the `Middleware` class to what it was before, I should not have changed it.

**Comment by tmbo** [comment]
Thanks for tagging a new version. So with socketio 2.1.1 it should be fine to use engineio 3?

**Comment by miguelgrinberg** [comment]
Yes, that should have no problem, the 3.0 release of engineio remains compatible with this package (not counting bugs!)

**Comment by miguelgrinberg** [comment]
I haven't released the package yet, working on it. The tag will match the package as I release it.

**Comment by miguelgrinberg** [comment]
version 2.1.1 is now released on pypi.

**Comment by tmbo** [comment]
Works like a charm, thanks a lot for that quick fix :rocket:
