### ISSUE TITLE
AttributeError: module 'socketio' has no attribute 'Client'

### ISSUE THREAD

**Issue by plaa** [miguelgrinberg/python-socketio#264]
I'm trying to use the Socket.io client.  I've seen #190 and #198 and I've made sure I've installed `python-socketio` and don't have `socketio` installed.

I run the test program:

```
print("one")

import socketio

print("two")
print(socketio)
print(dir(socketio))
print("---")

sio = socketio.Client()

print("three")
```

and I get the output:

```
$ python3 socket.py
one
one
two
<module 'socketio' from '/usr/local/lib/python3.7/site-packages/socketio/__init__.py'>
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'sys']
---
Traceback (most recent call last):
  File "socket.py", line 3, in <module>
    import socketio
  File "/usr/local/lib/python3.7/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 5, in <module>
    import engineio
  File "/usr/local/lib/python3.7/site-packages/engineio/__init__.py", line 7, in <module>
    from .asyncio_server import AsyncServer
  File "/usr/local/lib/python3.7/site-packages/engineio/asyncio_server.py", line 1, in <module>
    import asyncio
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 23, in <module>
    import socket
  File "/Users/sampo/Odysseus/odysseus-python/socket.py", line 10, in <module>
    sio = socketio.Client()
AttributeError: module 'socketio' has no attribute 'Client'
````

I have no idea why `one` is printed out twice.

I'm running on MacOS Mojave with Python 3.7.2 installed with Homebrew.  Some diagnostics:

```
$ python3 --version
Python 3.7.2

$ pip3 freeze
python-engineio==3.4.3
python-socketio==3.1.2
six==1.12.0

$ pip3 show python-socketio
Name: python-socketio
Version: 3.1.2
Summary: Socket.IO server
Home-page: http://github.com/miguelgrinberg/python-socketio/
Author: Miguel Grinberg
Author-email: miguelgrinberg50@gmail.com
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires: python-engineio, six
Required-by:

$ pip3 show socketio

$ head -n20 /usr/local/lib/python3.7/site-packages/socketio/client.py | tail -n7

class Client(object):
    """A Socket.IO client.

    This class implements a fully compliant Socket.IO web client with support
    for websocket and long-polling transports.

$ tail /usr/local/lib/python3.7/site-packages/socketio/__init__.py

__version__ = '3.1.2'

__all__ = ['__version__', 'Client', 'Server', 'BaseManager', 'PubSubManager',
           'KombuManager', 'RedisManager', 'ZmqManager', 'Namespace',
           'ClientNamespace', 'WSGIApp', 'Middleware']
if AsyncServer is not None:  # pragma: no cover
    __all__ += ['AsyncClient', 'AsyncServer', 'AsyncNamespace',
                'AsyncClientNamespace', 'AsyncManager', 'AsyncRedisManager',
                'ASGIApp', 'get_tornado_handler']
```

Thanks for any assistance!

**Comment by miguelgrinberg** [comment]
You can't have a file named `socket.py` in your top-level directory, because it shadows the socket module from the Python standard library. Rename that file to some other name and try again.

**Comment by plaa** [comment]
Thanks. I just realized the same thing as I was testing another socket.io library and it _still_ printed out the `one`. Had no idea you could accidentally override system libraries in Python.

**Comment by miguelgrinberg** [comment]
yeah, I've seen people trip on this so many times! What I found to be a good practice to avoid this type of issue is to not put your application in the top-level directory of your project. Instead, put it inside a package, and just put a `run.py` or similar in the top-level that imports the package. Inside the application package you don't have a problem because now those modules are not in the Python path, `import socket` goes to Python, and `from app import socket` goes to your app. No collisions.

**Comment by Rolandisimo** [comment]
I get the same issue with the filename being called `myFile.py`. 

```
import socketio
sio = socketio.Client() // AttributeError: module 'socketio' has no attribute 'Client'
```

**Comment by miguelgrinberg** [comment]
@Rolandisimo Are you sure the package `python-socketio` is installed? Check the output of `pip freeze`. I bet you don't have it and instead have something other unrelated socketio package.

**Comment by Rolandisimo** [comment]
@miguelgrinberg I see what happened. I opened https://python-socketio.readthedocs.io/en/latest/intro.html# and didn't find any install command . So instead I inferred this `import socketio` to be `pip install socketio` which seems to be either deprecated or something unrelated.
Fixed by running `pip3 install python-socketio`

**Comment by allenmixon** [comment]
I'm getting the same error using socket io with kivy. The application works great on my desktop but when I load it onto my andriod device using buildozer I get the following in the logcat file:
```

 python  :  Traceback (most recent call last):
 python  :    File "/home/allen/Desktop/GTCount_Buildozer/.buildozer/android/app/main.py", line 23, in <module>
 python  :  AttributeError: module 'socketio' has no attribute 'Client'
 python  : Python for android ended.
```
Thanks.

**Comment by brandonrussell270** [comment]
@miguelgrinberg Downgrading to 3.11.2 and 4.4.0 resolved the AttributeError: 'module' object has no attribute 'main_thread'. I also am using python 2.7. At this time, our project does not support python 3.

**Comment by shivam-S-bisht** [comment]
This is from the official documentation of socket.io. pip install "python-socketio[client]" ☺

**Comment by Ash-S** [comment]
Hi, Please help me, since I am facing the similar issue.
**_Traceback )most recent call last):
  File "singleboard.py", line 52, in <module>
     @socketio.event
AttributeError: 'SocketIO' object has no attribute 'event'_**

Please suggest! Thanks.

**Comment by miguelgrinberg** [comment]
@Ash-S the `event` decorator is relatively new. Are you using a recent version?

**Comment by Ash-S** [comment]
Hi @miguelgrinberg seems, its latest. 
Would you please let me know more I need to check to resolve this error? pip freeze gives me this....

![image](https://user-images.githubusercontent.com/11657541/112969499-41c5e480-9188-11eb-94cb-1e40792ca311.png)

Please suggest.

**Comment by miguelgrinberg** [comment]
@Ash-S Check the change log: https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/CHANGES.md. The event decorator was added in version 5 of Flask-SocketIO.

**Comment by Ash-S** [comment]
Thank you @miguelgrinberg for your suggestion. I was needed to update python version and seems, it works with v3.7.0 which updated flask-socket >= 5.0.0. Thanks.

**Comment by gbizeau** [comment]
> @miguelgrinberg I see what happened. I opened https://python-socketio.readthedocs.io/en/latest/intro.html# and didn't find any install command . So instead I inferred this `import socketio` to be `pip install socketio` which seems to be either deprecated or something unrelated. Fixed by running `pip install python-socketio`

This is indeed the fix, Just make sure you uninstall socketio and python-socketio then install only python-socketio

**Comment by juanrd99** [comment]
> This is indeed the fix, Just make sure you uninstall socketio and python-socketio then install only python-socketio

Thanks for the suggestion, fixed my problem removing socketio & python-socketio and then installing just python-socketio

**Comment by Javi2400** [comment]
i have a problem i want to use socketio on a raspberry pi 4 model b and i get an error:
Traceback (most recent call last):
sio = socketio.Client()
AttributeError: module 'socketio' has no attribute 'Client'
i am using 
python-engineio == 3.11.2
python-engineio-client ==1.1
python-socketio == 4.4.0
how can I fix that?
thanks
