### ISSUE TITLE
Handling of binary data fails sometimes

### ISSUE THREAD

**Issue by Schnodderbalken** [miguelgrinberg/python-socketio#37]
After updating flask-socketio from 1.2 to 2.6 I have a strange error that comes up occasionally when there are more than a few threads that handle a binary message from a socket.io client. I get the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/maRcbook/Library/Python/3.5/lib/python/site-packages/socketio/server.py", line 442, in _handle_eio_message
    self._binary_packet.reconstruct_binary(self._attachments)
AttributeError: 'NoneType' object has no attribute 'reconstruct_binary'
```

I just noticed is has nothing to do with the upgrade of flask-socketio. I upgraded python from 3.4 to 3.5 as well and this is probably the cause. Downgrading flask-socketio did not make it work. So it probably has to do with python-socketio for python 3.5

**Comment by Schnodderbalken** [comment]
If I change server.py l. 437 to `if self._attachment_count > 0 and self._binary_packet != None:` it crashes at another stage

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/maRcbook/Library/Python/3.5/lib/python/site-packages/socketio/server.py", line 454, in _handle_eio_message
    pkt = packet.Packet(encoded_packet=data)
  File "/Users/maRcbook/Library/Python/3.5/lib/python/site-packages/socketio/packet.py", line 32, in __init__
    self.attachment_count = self.decode(encoded_packet)
  File "/Users/maRcbook/Library/Python/3.5/lib/python/site-packages/socketio/packet.py", line 73, in decode
    self.packet_type = int(ep[0:1])
ValueError: invalid literal for int() with base 10: b'%'`

I wonder why this only happens since I upgrade Python to 3.5

**Comment by miguelgrinberg** [comment]
Could you add a print statement for the variable `ep` right before line 73 in packet.py? Not sure if this is important or not, but that might provide a clue to this problem.

**Comment by Schnodderbalken** [comment]
Sure! The content of ep is a byte-array of a pdf file. It looks like this:

`b'%PDF-1.3\n%\xc4\xe5\xf2\xe5\xeb\xa7\xf3\xa0\xd0\xc4\xc6\n4 0 obj\n<< /Length 5 0 R /Filter /FlateDecode >>\nstream\nx\x01+T\x08T(T\xd0\x0fH-JN-()M\xccQ(\xca\x04\n\x98Z\x1a*\x18\x00\xa1\x85\x891\x98N\xceU\xd0\xf7\xcc5Tp\xc9\x07\xaa\x0f\x04\x00\x95\xb4\r\xfd\nendstream\nendobj\n5 0 obj\n54\nendobj\n2 0 obj\n<< /Type /Page /Parent 3 0 R /Resources 6 0 R /Contents 4 0 R /MediaBox [0 0 591 843]\n>>\nendobj\n6 0 obj\n<< /ProcSet [ /PDF /ImageB /ImageC /ImageI ] /XObject << /Im1 7 0 R >> >>\nendobj\n7 0 obj\n<< /Length 8 0 R /Type /XObject /Subtype /Image /Width 3284 /Height 4688 /ColorSpace\n9 0 R /BitsPerComponent 1 /Filter /FlateDecode >>\nstream\nx\x01\xec\xbd\xcd\x8e\xdbH\xda\xb6I\x95\x80f-\x1a\xc5m/<E\`

and so on (becomes unreadable from there on)

**Comment by miguelgrinberg** [comment]
Are you doing anything with PDF files?

**Comment by Schnodderbalken** [comment]
Yes, the client sends them via websocket in binary format to the server.

**Comment by miguelgrinberg** [comment]
Are you sending the PDF as a standalone payload, or is it part of a larger data structure, maybe something like `{'foo': 'bar', 'pdf': <pdf-binary-data>}`?

**Comment by Schnodderbalken** [comment]
This is the signature of the function that handles the client message.

`def _declareUserCommandRoute(self, controller):
		@self._socketio.on(controller.client_command_payload)
		def response(json_data, type=None, nonce=None):
[...]`

If I print the content of the first parameter (json_data) it says:
`{'data': b'pdfbinarycontent', 'method': 'post'}`

So to answer your question: as a part of a larger data structure.

**Comment by miguelgrinberg** [comment]
Yeah, sounds like when several of these PDF attachments are flying the server sometimes loses one and treats it as a standalone message. This is useful, I think I have enough to reproduce the problem. Thanks.

**Comment by Schnodderbalken** [comment]
Okay cool! If you need further information like a concrete payload that causes the problem let me know. Thanks in advance.

**Comment by miguelgrinberg** [comment]
> And then again it only happens when I have multiple threads running that try to accept the client messages.

Can you explain this statement in detail? Are you talking about server-side threads or client-side?

**Comment by Schnodderbalken** [comment]
Yes, it's about server-side threads. I handle every request in a separate thread as I have resource hungry calculations running (OCR) that should not block further incoming requests.

**Comment by miguelgrinberg** [comment]
Not sure I understand how your use of threads affects the internals of the socket.io server. You are instantiating only one server, correct? Can you show me the code that spawns your threads?

**Comment by Schnodderbalken** [comment]
If it helps you to reproduce the problem I could even send you a script that reproduces the problem (that will take some days though because I am currently not at home)

**Comment by miguelgrinberg** [comment]
> The "on"-Method that reacts on client requests spawns new threads.

Okay, this should be fine, in fact the functions attached to "on" decorators are executed in independent threads anyway.

If you can send me an example that reproduces the problem that would be most helpful. Thanks!

**Comment by Schnodderbalken** [comment]
It was a hard task but I managed to boil everything down to a few lines of code (in js and in python as well). http://s000.tinyupload.com/index.php?file_id=69252726138999738284 here is a zip containing the js file, the py file and two client-side dependencies (jquery and socketio). If you have any problems launching it or anything, let me know. I used tinyupload the first time, I hope the file stays there long enough.

**Comment by miguelgrinberg** [comment]
Thanks, got the file. How do I trigger the error? Select a file and keep doing it until it fails?

**Comment by Schnodderbalken** [comment]
On my machine (MacBook Pro 2013) I had to just choose many (about 15) files (each at least 1mb big I think) in the file dialog. That triggers socketio to send it to the server and immediately led to the errors explained in my first post.

**Comment by Schnodderbalken** [comment]
I chose the files all at once in the dialog

**Comment by miguelgrinberg** [comment]
Can I ask you to retest with the master branch? I think the fix that I just made will address the problem with the binary attachments. Thanks a lot, the example you provided was immensely helpful.

**Comment by Schnodderbalken** [comment]
Awesome! It works. Thanks for the uncomplicated way of communicating and the tremendous speed! 👍
